ALTER TABLE users
    ADD COLUMN first_name VARCHAR(80) NULL,
    ADD COLUMN last_name  VARCHAR(80) NULL,
    ADD COLUMN city       VARCHAR(120) NULL,
    ADD COLUMN address    VARCHAR(255) NULL,
    ADD COLUMN role       VARCHAR(32) NOT NULL DEFAULT 'CARE_SEEKER';
